# -*- coding: utf-8 -*-
"""codesoft1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ytsQkgb9AUVNcWyFfJfLdxMash41tF9F
"""

a=int(input("Enter 1st number:"))
b=int(input("Enter 2nd number:"))
choice = input("Enter the operation (+, -, *, /): ")
if choice=="+":
    print(a+b)
elif choice=="-":
    print(a-b)
elif choice=="*":
    print(a*b)
elif choice == "/":
    print(a/b)